# Generated by Django 5.1.4 on 2024-12-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
